export const ddds = [
  { code: "📲", flag: "", country: "DDD" },
  { code: "+1", flag: "/flags/us.svg", country: "Estados Unidos" },
  { code: "+55", flag: "/flags/br.svg", country: "Brasil" },
  { code: "+44", flag: "/flags/uk.svg", country: "Reino Unido" },
  { code: "+33", flag: "/flags/fr.svg", country: "França" },
  { code: "+49", flag: "/flags/de.svg", country: "Alemanha" },
  { code: "+39", flag: "/flags/it.svg", country: "Itália" },
  { code: "+34", flag: "/flags/es.svg", country: "Espanha" },
  { code: "+81", flag: "/flags/jp.svg", country: "Japão" },
  { code: "+86", flag: "/flags/cn.svg", country: "China" },
  { code: "+91", flag: "/flags/in.svg", country: "Índia" },
  { code: "+7", flag: "/flags/ru.svg", country: "Rússia" },
  { code: "+61", flag: "/flags/au.svg", country: "Austrália" },
  { code: "+1", flag: "/flags/ca.svg", country: "Canadá" },
  { code: "+82", flag: "/flags/kr.svg", country: "Coreia do Sul" },
  { code: "+31", flag: "/flags/nl.svg", country: "Países Baixos" },
  { code: "+47", flag: "/flags/no.svg", country: "Noruega" },
  { code: "+46", flag: "/flags/se.svg", country: "Suécia" },
  { code: "+41", flag: "/flags/ch.svg", country: "Suíça" },
  { code: "+32", flag: "/flags/be.svg", country: "Bélgica" },
  { code: "+65", flag: "/flags/sg.svg", country: "Singapura" },
  { code: "+52", flag: "/flags/mx.svg", country: "México" },
  { code: "+27", flag: "/flags/za.svg", country: "África do Sul" },
  { code: "+90", flag: "/flags/tr.svg", country: "Turquia" },
  { code: "+54", flag: "/flags/ar.svg", country: "Argentina" },
  { code: "+30", flag: "/flags/gr.svg", country: "Grécia" },
  { code: "+351", flag: "/flags/pt.svg", country: "Portugal" },
  { code: "+48", flag: "/flags/pl.svg", country: "Polônia" },
  { code: "+598", flag: "/flags/uy.svg", country: "Uruguai" },
  { code: "+60", flag: "/flags/my.svg", country: "Malásia" },
];
